# Generated by Django 6.0.5 on 2026-05-22 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('origin', models.CharField(max_length=80)),
                ('destination', models.CharField(max_length=80)),
                ('tagline', models.CharField(max_length=160)),
                ('mood', models.CharField(choices=[('coastal', 'Coastal'), ('mountain', 'Mountain'), ('city', 'City'), ('heritage', 'Heritage'), ('wild', 'Wild')], max_length=20)),
                ('start_date', models.DateField()),
                ('days', models.PositiveSmallIntegerField()),
                ('distance_km', models.PositiveIntegerField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cover_color', models.CharField(default='#0f766e', max_length=32)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_featured', 'start_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=220)),
                ('drive_time', models.CharField(max_length=40)),
                ('overnight', models.BooleanField(default=False)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.trip')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('trip', 'order')},
            },
        ),
    ]
